services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    # Port 4000 dibuka di dalam jaringan docker agar bisa dipanggil Nginx
    expose:
      - "4000"
    # Jika Anda masih ingin akses backend via Postman lewat port 4000, biarkan ini:
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    restart: always